eureka:
 client:
  service-url:
    #defaultZone: http://eureka-primary:8091/eureka/,http://eureka-secondary:8092/eureka/,http://eureka-tertiary:8093/eureka/
    defaultZone: http://eureka-primary:8801/eureka/,http://eureka-secondary:8802/eureka/
igv: 0.4
